# Generated by Django 5.0.6 on 2024-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadb',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
